name: Create WordPress theme Zip file

on:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    name: Build Theme Artifact
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Generate theme artifact
        run: |
          mkdir -p release/daandev
          rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" release/daandev/ --delete --delete-excluded
          cd "${GITHUB_WORKSPACE}/release" || exit
          zip -r "${GITHUB_WORKSPACE}/daandev.zip" .

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/daandev.zip
          asset_name: daandev.zip
          asset_content_type: application/zip
